In [2]:
import pandas as pd

In [ ]:
df = pd.read_csv ("福岡支店.csv", encoding="cp932")

df

,契約番号,請求回,請求日,顧客コード,前受金金額,請求金額,消費税,前受金からの取崩金額,差引請求額,担当部署名,売上集計区分,契約月数,延長区分,契約期間
0,B21007500,51,2025/9/30,7635,0,12200,1220,0,13420,福岡支店,レンタル法人,60,新規,12ヶ月以上
1,B21007500,52,2025/10/31,7635,0,12200,1220,0,13420,福岡支店,レンタル法人,60,新規,12ヶ月以上
2,B21007500,53,2025/11/30,7635,0,12200,1220,0,13420,福岡支店,レンタル法人,60,新規,12ヶ月以上
3,B21007500,54,2025/12/31,7635,0,12200,1220,0,13420,福岡支店,レンタル法人,60,新規,12ヶ月以上
4,B21007500,55,2026/1/31,7635,0,12200,1220,0,13420,福岡支店,レンタル法人,60,新規,12ヶ月以上
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8904,B26002826,2,2026/4/30,14073,0,47100,4710,0,51810,福岡支店,レンタル法人,36,新規,12ヶ月以上
8905,B26002826,3,2026/5/31,14073,0,47100,4710,0,51810,福岡支店,レンタル法人,36,新規,12ヶ月以上
8906,B26002826,4,2026/6/30,14073,0,47100,4710,0,51810,福岡支店,レンタル法人,36,新規,12ヶ月以上
8907,B26002826,5,2026/7/31,14073,0,47100,4710,0,51810,福岡支店,レンタル法人,36,新規,12ヶ月以上
8908,B26002826,6,2026/8/31,14073,0,47100,4710,0,51810,福岡支店,レンタル法人,36,新規,12ヶ月以上

In [13]:
df["請求金額"].sum()

np.int64(255920690)

In [16]:
df["請求月"] =pd.to_datetime( df["請求日"]).dt.to_period("M")
df

,契約番号,請求回,請求日,顧客コード,前受金金額,請求金額,消費税,前受金からの取崩金額,差引請求額,担当部署名,売上集計区分,契約月数,延長区分,契約期間,請求月
0,B21007500,51,2025/9/30,7635,0,12200,1220,0,13420,福岡支店,レンタル法人,60,新規,12ヶ月以上,2025-09
1,B21007500,52,2025/10/31,7635,0,12200,1220,0,13420,福岡支店,レンタル法人,60,新規,12ヶ月以上,2025-10
2,B21007500,53,2025/11/30,7635,0,12200,1220,0,13420,福岡支店,レンタル法人,60,新規,12ヶ月以上,2025-11
3,B21007500,54,2025/12/31,7635,0,12200,1220,0,13420,福岡支店,レンタル法人,60,新規,12ヶ月以上,2025-12
4,B21007500,55,2026/1/31,7635,0,12200,1220,0,13420,福岡支店,レンタル法人,60,新規,12ヶ月以上,2026-01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8904,B26002826,2,2026/4/30,14073,0,47100,4710,0,51810,福岡支店,レンタル法人,36,新規,12ヶ月以上,2026-04
8905,B26002826,3,2026/5/31,14073,0,47100,4710,0,51810,福岡支店,レンタル法人,36,新規,12ヶ月以上,2026-05
8906,B26002826,4,2026/6/30,14073,0,47100,4710,0,51810,福岡支店,レンタル法人,36,新規,12ヶ月以上,2026-06
8907,B26002826,5,2026/7/31,14073,0,47100,4710,0,51810,福岡支店,レンタル法人,36,新規,12ヶ月以上,2026-07
8908,B26002826,6,2026/8/31,14073,0,47100,4710,0,51810,福岡支店,レンタル法人,36,新規,12ヶ月以上,2026-08

In [17]:
df.groupby("請求月")["請求金額"].sum()

請求月
2025-09    30826224
2025-10    33771570
2025-11    33083513
2025-12    24930876
2026-01    23071392
2026-02    16390115
2026-03    26113855
2026-04    13872165
2026-05    13778065
2026-06    13620815
2026-07    13318350
2026-08    13143750
Freq: M, Name: 請求金額, dtype: int64

In [18]:
df = pd.read_csv("熊本支店.csv",encoding="cp932")

In [24]:
areas = ["熊本","大阪","福岡"]
df_all = pd.DataFrame()
for area in areas:
    df = pd.read_csv(f"{area}支店.csv",encoding="cp932")
    df_all = pd.concat([df_all, df])
df_all["担当部署名"].value_counts()

担当部署名
福岡支店    8909
熊本支店    7881
大阪支店     845
Name: count, dtype: int64

In [25]:
df_all["請求月"] =pd.to_datetime( df_all["請求日"]).dt.to_period("M")
df_all

,契約番号,請求回,請求日,顧客コード,前受金金額,請求金額,消費税,前受金からの取崩金額,差引請求額,担当部署名,売上集計区分,契約月数,延長区分,契約期間,請求月
0,B22012829,39,2025/9/30,10754,0,75200,7520,0,82720,熊本支店,レンタル法人,49,新規,12ヶ月以上,2025-09
1,B22012829,40,2025/10/31,10754,0,75200,7520,0,82720,熊本支店,レンタル法人,49,新規,12ヶ月以上,2025-10
2,B22012829,41,2025/11/30,10754,0,75200,7520,0,82720,熊本支店,レンタル法人,49,新規,12ヶ月以上,2025-11
3,B22012829,42,2025/12/31,10754,0,75200,7520,0,82720,熊本支店,レンタル法人,49,新規,12ヶ月以上,2025-12
4,B22012829,43,2026/1/31,10754,0,75200,7520,0,82720,熊本支店,レンタル法人,49,新規,12ヶ月以上,2026-01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8904,B26002826,2,2026/4/30,14073,0,47100,4710,0,51810,福岡支店,レンタル法人,36,新規,12ヶ月以上,2026-04
8905,B26002826,3,2026/5/31,14073,0,47100,4710,0,51810,福岡支店,レンタル法人,36,新規,12ヶ月以上,2026-05
8906,B26002826,4,2026/6/30,14073,0,47100,4710,0,51810,福岡支店,レンタル法人,36,新規,12ヶ月以上,2026-06
8907,B26002826,5,2026/7/31,14073,0,47100,4710,0,51810,福岡支店,レンタル法人,36,新規,12ヶ月以上,2026-07
8908,B26002826,6,2026/8/31,14073,0,47100,4710,0,51810,福岡支店,レンタル法人,36,新規,12ヶ月以上,2026-08

In [29]:
df_all.groupby("請求月")["請求金額"].sum().reset_index()

        請求月      請求金額
0   2025-09  56561923
1   2025-10  63962684
2   2025-11  59455559
3   2025-12  47675523
4   2026-01  52133043
5   2026-02  41021192
6   2026-03  43612093
7   2026-04  26968386
8   2026-05  25104395
9   2026-06  24736274
10  2026-07  24305559
11  2026-08  23059129