In [7]:
import pandas as pd

In [8]:
df = pd.read_csv ("福岡支店.csv", encoding="cp932")

df

,契約番号,請求回,請求日,顧客コード,前受金金額,請求金額,消費税,前受金からの取崩金額,差引請求額,担当部署名,売上集計区分,契約月数,延長区分,契約期間
0,B21007500,51,2025/9/30,7635,0,12200,1220,0,13420,福岡支店,レンタル法人,60,新規,12ヶ月以上
1,B21007500,52,2025/10/31,7635,0,12200,1220,0,13420,福岡支店,レンタル法人,60,新規,12ヶ月以上
2,B21007500,53,2025/11/30,7635,0,12200,1220,0,13420,福岡支店,レンタル法人,60,新規,12ヶ月以上
3,B21007500,54,2025/12/31,7635,0,12200,1220,0,13420,福岡支店,レンタル法人,60,新規,12ヶ月以上
4,B21007500,55,2026/1/31,7635,0,12200,1220,0,13420,福岡支店,レンタル法人,60,新規,12ヶ月以上
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8904,B26002826,2,2026/4/30,14073,0,47100,4710,0,51810,福岡支店,レンタル法人,36,新規,12ヶ月以上
8905,B26002826,3,2026/5/31,14073,0,47100,4710,0,51810,福岡支店,レンタル法人,36,新規,12ヶ月以上
8906,B26002826,4,2026/6/30,14073,0,47100,4710,0,51810,福岡支店,レンタル法人,36,新規,12ヶ月以上
8907,B26002826,5,2026/7/31,14073,0,47100,4710,0,51810,福岡支店,レンタル法人,36,新規,12ヶ月以上
8908,B26002826,6,2026/8/31,14073,0,47100,4710,0,51810,福岡支店,レンタル法人,36,新規,12ヶ月以上

In [9]:
df["請求金額"].sum()

np.int64(255920690)

In [10]:
df["請求月"] =pd.to_datetime( df["請求日"]).dt.to_period("M")
df

,契約番号,請求回,請求日,顧客コード,前受金金額,請求金額,消費税,前受金からの取崩金額,差引請求額,担当部署名,売上集計区分,契約月数,延長区分,契約期間,請求月
0,B21007500,51,2025/9/30,7635,0,12200,1220,0,13420,福岡支店,レンタル法人,60,新規,12ヶ月以上,2025-09
1,B21007500,52,2025/10/31,7635,0,12200,1220,0,13420,福岡支店,レンタル法人,60,新規,12ヶ月以上,2025-10
2,B21007500,53,2025/11/30,7635,0,12200,1220,0,13420,福岡支店,レンタル法人,60,新規,12ヶ月以上,2025-11
3,B21007500,54,2025/12/31,7635,0,12200,1220,0,13420,福岡支店,レンタル法人,60,新規,12ヶ月以上,2025-12
4,B21007500,55,2026/1/31,7635,0,12200,1220,0,13420,福岡支店,レンタル法人,60,新規,12ヶ月以上,2026-01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8904,B26002826,2,2026/4/30,14073,0,47100,4710,0,51810,福岡支店,レンタル法人,36,新規,12ヶ月以上,2026-04
8905,B26002826,3,2026/5/31,14073,0,47100,4710,0,51810,福岡支店,レンタル法人,36,新規,12ヶ月以上,2026-05
8906,B26002826,4,2026/6/30,14073,0,47100,4710,0,51810,福岡支店,レンタル法人,36,新規,12ヶ月以上,2026-06
8907,B26002826,5,2026/7/31,14073,0,47100,4710,0,51810,福岡支店,レンタル法人,36,新規,12ヶ月以上,2026-07
8908,B26002826,6,2026/8/31,14073,0,47100,4710,0,51810,福岡支店,レンタル法人,36,新規,12ヶ月以上,2026-08

In [11]:
df.groupby("請求月")["請求金額"].sum()

請求月
2025-09    30826224
2025-10    33771570
2025-11    33083513
2025-12    24930876
2026-01    23071392
2026-02    16390115
2026-03    26113855
2026-04    13872165
2026-05    13778065
2026-06    13620815
2026-07    13318350
2026-08    13143750
Freq: M, Name: 請求金額, dtype: int64

In [12]:
df = pd.read_csv("熊本支店.csv",encoding="cp932")

In [13]:
areas = ["熊本","大阪","福岡"]
df_all = pd.DataFrame()
for area in areas:
    df = pd.read_csv(f"{area}支店.csv",encoding="cp932")
    df_all = pd.concat([df_all, df])
df_all["担当部署名"].value_counts()

担当部署名
福岡支店    8909
熊本支店    7881
大阪支店     845
Name: count, dtype: int64

In [14]:
df_all["請求月"] =pd.to_datetime( df_all["請求日"]).dt.to_period("M")
df_all

,契約番号,請求回,請求日,顧客コード,前受金金額,請求金額,消費税,前受金からの取崩金額,差引請求額,担当部署名,売上集計区分,契約月数,延長区分,契約期間,請求月
0,B22012829,39,2025/9/30,10754,0,75200,7520,0,82720,熊本支店,レンタル法人,49,新規,12ヶ月以上,2025-09
1,B22012829,40,2025/10/31,10754,0,75200,7520,0,82720,熊本支店,レンタル法人,49,新規,12ヶ月以上,2025-10
2,B22012829,41,2025/11/30,10754,0,75200,7520,0,82720,熊本支店,レンタル法人,49,新規,12ヶ月以上,2025-11
3,B22012829,42,2025/12/31,10754,0,75200,7520,0,82720,熊本支店,レンタル法人,49,新規,12ヶ月以上,2025-12
4,B22012829,43,2026/1/31,10754,0,75200,7520,0,82720,熊本支店,レンタル法人,49,新規,12ヶ月以上,2026-01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8904,B26002826,2,2026/4/30,14073,0,47100,4710,0,51810,福岡支店,レンタル法人,36,新規,12ヶ月以上,2026-04
8905,B26002826,3,2026/5/31,14073,0,47100,4710,0,51810,福岡支店,レンタル法人,36,新規,12ヶ月以上,2026-05
8906,B26002826,4,2026/6/30,14073,0,47100,4710,0,51810,福岡支店,レンタル法人,36,新規,12ヶ月以上,2026-06
8907,B26002826,5,2026/7/31,14073,0,47100,4710,0,51810,福岡支店,レンタル法人,36,新規,12ヶ月以上,2026-07
8908,B26002826,6,2026/8/31,14073,0,47100,4710,0,51810,福岡支店,レンタル法人,36,新規,12ヶ月以上,2026-08

In [16]:
jittsseki=df_all.groupby("請求月")["請求金額"].sum().reset_index()
jittsseki

        請求月      請求金額
0   2025-09  56561923
1   2025-10  63962684
2   2025-11  59455559
3   2025-12  47675523
4   2026-01  52133043
5   2026-02  41021192
6   2026-03  43612093
7   2026-04  26968386
8   2026-05  25104395
9   2026-06  24736274
10  2026-07  24305559
11  2026-08  23059129

In [3]:
import pandas as pd
yosan = pd.read_excel("yosan_15.xlsx")
yosan

            月      月間予算
0  2025-09-01  56561923
1  2025-10-01  63962684
2  2025-11-01  59455559
3  2025-12-01  47675523
4  2026-01-01  52133043
5  2026-02-01  60040000
6  2026-03-01  60041268
7  2026-04-01  60040000
8  2026-05-01  60040000
9  2026-06-01  60040000
10 2026-07-01  60040000
11 2026-08-01  60040000

In [4]:
yosan["予算月"] =pd.to_datetime( yosan["月"]).dt.to_period("M")
yosan

            月      月間予算      予算月
0  2025-09-01  56561923  2025-09
1  2025-10-01  63962684  2025-10
2  2025-11-01  59455559  2025-11
3  2025-12-01  47675523  2025-12
4  2026-01-01  52133043  2026-01
5  2026-02-01  60040000  2026-02
6  2026-03-01  60041268  2026-03
7  2026-04-01  60040000  2026-04
8  2026-05-01  60040000  2026-05
9  2026-06-01  60040000  2026-06
10 2026-07-01  60040000  2026-07
11 2026-08-01  60040000  2026-08

In [27]:
# 結合（merge）
merged_df = pd.merge(jittsseki, yosan, left_on='請求月', right_on='予算月', how='left')

# 結果表示
merged_df = merged_df.drop("月", axis=1)

In [32]:
merged_df["月間予算不足額"] = merged_df["月間予算"] - merged_df["請求金額"]
merged_df["予算月"] = merged_df["予算月"].astype(str)
json_str = merged_df[["予算月","月間予算不足額"]].to_json(orient='records', force_ascii=False)  # force_ascii=False で日本語をそのまま出力
json_str

'[{"予算月":"2025-09","月間予算不足額":0},{"予算月":"2025-10","月間予算不足額":0},{"予算月":"2025-11","月間予算不足額":0},{"予算月":"2025-12","月間予算不足額":0},{"予算月":"2026-01","月間予算不足額":0},{"予算月":"2026-02","月間予算不足額":19018808},{"予算月":"2026-03","月間予算不足額":16429175},{"予算月":"2026-04","月間予算不足額":33071614},{"予算月":"2026-05","月間予算不足額":34935605},{"予算月":"2026-06","月間予算不足額":35303726},{"予算月":"2026-07","月間予算不足額":35734441},{"予算月":"2026-08","月間予算不足額":36980871}]'

In [19]:
merged_df["月間予算不足額"].sum()

np.int64(211474240)

In [20]:
from pathlib import Path

folder_path = Path(r"実績")

# ファイルだけを取得
files = [f for f in folder_path.iterdir() if f.is_file()]
files

[WindowsPath('実績/大阪支店.csv'),
 WindowsPath('実績/熊本支店.csv'),
 WindowsPath('実績/福岡支店.csv')]

In [22]:
df_all = pd.DataFrame()
for file in folder_path.iterdir():
    if file.is_file():
        df = pd.read_csv(file,encoding="cp932")
        df_all = pd.concat([df_all, df])
        print(file)
df_all

実績\大阪支店.csv
実績\熊本支店.csv
実績\福岡支店.csv

,契約番号,請求回,請求日,顧客コード,前受金金額,請求金額,消費税,前受金からの取崩金額,差引請求額,担当部署名,売上集計区分,契約月数,延長区分,契約期間
0,B22003986,43,2025/9/30,9474,0,3000,300,0,3300,大阪支店,レンタル法人,60,新規,12ヶ月以上
1,B22003986,44,2025/10/31,9474,0,3000,300,0,3300,大阪支店,レンタル法人,60,新規,12ヶ月以上
2,B22003986,45,2025/11/30,9474,0,3000,300,0,3300,大阪支店,レンタル法人,60,新規,12ヶ月以上
3,B22003986,46,2025/12/31,9474,0,3000,300,0,3300,大阪支店,レンタル法人,60,新規,12ヶ月以上
4,B22003986,47,2026/1/31,9474,0,3000,300,0,3300,大阪支店,レンタル法人,60,新規,12ヶ月以上
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8904,B26002826,2,2026/4/30,14073,0,47100,4710,0,51810,福岡支店,レンタル法人,36,新規,12ヶ月以上
8905,B26002826,3,2026/5/31,14073,0,47100,4710,0,51810,福岡支店,レンタル法人,36,新規,12ヶ月以上
8906,B26002826,4,2026/6/30,14073,0,47100,4710,0,51810,福岡支店,レンタル法人,36,新規,12ヶ月以上
8907,B26002826,5,2026/7/31,14073,0,47100,4710,0,51810,福岡支店,レンタル法人,36,新規,12ヶ月以上
8908,B26002826,6,2026/8/31,14073,0,47100,4710,0,51810,福岡支店,レンタル法人,36,新規,12ヶ月以上

In [ ]:
areas = ["熊本","大阪","福岡"]
df_all = pd.DataFrame()
for area in areas:
    df = pd.read_csv(f"{area}支店.csv",encoding="cp932")
    df_all = pd.concat([df_all, df])
df_all["担当部署名"].value_counts()